export const FINANCIAL_CLASSIFIER_VERSION = 1;
export const FINANCIAL_ALLOCATION_ALGORITHM_VERSION = 2;
export const FINANCIAL_PAGE_SIZE = 100;
export const FINANCIAL_SCAN_RESOURCE_LIMIT = 100;
export const FINANCIAL_SCAN_BUCKET_MS = 60 * 60 * 1000;
export const FINANCIAL_PAYOUT_OVERLAP_MS = 72 * 60 * 60 * 1000;
export const FINANCIAL_INITIAL_PAYOUT_LOOKBACK_MS = 7 * 24 * 60 * 60 * 1000;
export {
  FINANCIAL_CLASSIFICATION_JOB_MAX_ATTEMPTS,
  FINANCIAL_PAYOUT_JOB_MAX_ATTEMPTS,
  FINANCIAL_SCAN_JOB_MAX_ATTEMPTS,
  FINANCIAL_SOURCE_JOB_MAX_ATTEMPTS
} from '$lib/server/jobs/catalog';
export const FINANCIAL_RAW_TYPE_MAX_LENGTH = 100;
export const FINANCIAL_PROVIDER_ID_MAX_LENGTH = 255;
export const FINANCIAL_GENERATION_MAX = 2_147_483_647;

export const FINANCIAL_REPLAY_ID =
  `c${FINANCIAL_CLASSIFIER_VERSION}-a${FINANCIAL_ALLOCATION_ALGORITHM_VERSION}` as const;
